"set guifont=Inconsolata\ for\ Powerline:h15
let g:Powerline_symbols='fancy'
set encoding=utf-8
set t_Co=256
set fillchars+=stl:\ ,stlnc:\
set term=xterm-256color
set termencoding=utf-8
set guioptions=egmrt
"set guifont=Consolas\ for\ Powerline:h14
"set guifont=Droid\ Sans\ Mono\ for\ Powerline:h14
"set guifont=Inconsolata\ for\ Powerline:h14
"set guifont=DejaVu\ Sans\ Mono\ for\ Powerline:h15
set guifont=Monaco\ for\ Powerline:h14
"set guifont=Inconsolata\ for\ Powerline:h15
